adding env to steps

diff --git a/.github/workflows/check_violations.yml b/.github/workflows/check_violations.yml
--- a/.github/workflows/check_violations.yml
+++ b/.github/workflows/check_violations.yml
@@ -29,28 +29,34 @@ jobs:
             echo "::error::Comparison script failed"
             exit 1
           fi
-
-      - name: Process comparison results
-        id: process_results
-        run: |
-          if [ -f violation_result.txt ]; then
-            echo "VIOLATION_DETECTED=$(grep VIOLATION_DETECTED violation_result.txt | cut -d'=' -f2)" >> $GITHUB_ENV
-            echo "SIMILARITY=$(grep SIMILARITY violation_result.txt | cut -d'=' -f2)" >> $GITHUB_ENV
-            echo "VIOLATOR_URL=$(grep VIOLATOR_URL violation_result.txt | cut -d'=' -f2)" >> $GITHUB_ENV
-            echo "Results processed successfully"
-          else
-            echo "::error::violation_result.txt not found"
-            exit 1
-          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          ISSUE_NUMBER: ${{ github.event.issue.number }}
+      # - name: Process comparison results
+      #   id: process_results
+      #   run: |
+      #     if [ -f violation_result.txt ]; then
+      #       echo "VIOLATION_DETECTED=$(grep VIOLATION_DETECTED violation_result.txt | cut -d'=' -f2)" >> $GITHUB_ENV
+      #       echo "SIMILARITY=$(grep SIMILARITY violation_result.txt | cut -d'=' -f2)" >> $GITHUB_ENV
+      #       echo "VIOLATOR_URL=$(grep VIOLATOR_URL violation_result.txt | cut -d'=' -f2)" >> $GITHUB_ENV
+      #       echo "Results processed successfully"
+      #     else
+      #       echo "::error::violation_result.txt not found"
+      #       exit 1
+      #     fi
 
       - name: Echo result
         run: |
           echo "Violation Detected: ${{ env.VIOLATION_DETECTED }}"
           echo "Similarity: ${{ env.SIMILARITY }}"
           echo "Violator URL: ${{ env.VIOLATOR_URL }}"
-
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          VIOLATION_DETECTED: ${{ env.VIOLATION_DETECTED}}
+          SIMILARITY: ${{ env.SIMILARITY}}
+          VIOLATOR_URL: ${{ env.VIOLATOR_URL}}
       - name: Update README
-        if: env.VIOLATION_DETECTED == 'true'
+        if: ${{env.VIOLATION_DETECTED == 'true'}}
         run: |
           echo "Violation detected. Updating README..."
           python update_readme.py
@@ -65,3 +71,6 @@ jobs:
           git push
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          VIOLATION_DETECTED: ${{ env.VIOLATION_DETECTED}}
+          SIMILARITY: ${{ env.SIMILARITY}}
+          VIOLATOR_URL: ${{ env.VIOLATOR_URL}}
