new udpate

diff --git a/.github/workflows/check_violations.yml b/.github/workflows/check_violations.yml
--- a/.github/workflows/check_violations.yml
+++ b/.github/workflows/check_violations.yml
@@ -55,12 +55,25 @@ jobs:
           VIOLATION_DETECTED: ${{ env.VIOLATION_DETECTED}}
           SIMILARITY: ${{ env.SIMILARITY}}
           VIOLATOR_URL: ${{ env.VIOLATOR_URL}}
-      - name: Update README
+      - name : Run Updator
+        if: env.VIOLATION_DETECTED == 'true'
+        run: |
+          echo "Violation detected. Updating README..."
+          python update_readme.py
+          if [ $? -ne 0 ]; then
+            echo "::error::Failed to update README"
+            exit 1
+          fi
+        env:
+            VIOLATION_DETECTED: ${{ env.VIOLATION_DETECTED}}
+            SIMILARITY: ${{ env.SIMILARITY}}
+            VIOLATOR_URL: ${{ env.VIOLATOR_URL}}
+      - name: commit README
+        if: env.VIOLATION_DETECTED == 'true'
+
         uses: EndBug/add-and-commit@v9
         with:
             add: README.md
         env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             VIOLATION_DETECTED: ${{ env.VIOLATION_DETECTED}}
-            SIMILARITY: ${{ env.SIMILARITY}}
-            VIOLATOR_URL: ${{ env.VIOLATOR_URL}}
